### ISSUE TITLE
Bcrypt dependacy needs to be updated to 0.8.1 for node v0.12

### ISSUE THREAD

**Issue by ryan-wong** [waterlock/waterlock-local-auth#18]
Can you update your package.json file to use a newer  version of bcrypt?

**Comment by Globegitter** [comment]
@ryan-wong Should be fixed now with the latest commit.

**Comment by pascalzontrop** [comment]
I can confirm it works with node 0.12.0 after downloading the master and installing it locally. Could you please update your NPM registry?

**Comment by pzontrop** [comment]
I can confirm it works with node v0.12.0 after downloading the master and installing it locally. Could you please update your npm registry?

**Comment by rh0dium** [comment]
Hi there!

Could you please reopen this until the latest package is supports 0.12.  The current latests (0.0.5) still points back to bcrypt 0.7.8.   Furthermore installing via githhub doesn't appear to work.

    npm i waterlock/waterlock-auth --save

Errors:  *ERROR: Repository not found.*

    npm WARN package.json assert@1.3.0 assert is also the name of a node core module.
    npm ERR! git clone --template=/Users/sklass/.npm/_git-remotes/_templates --mirror git://github.com/waterlock/waterlock-auth /Users/sklass/.npm/_git-remotes/git-github-com-waterlock-waterlock-auth-dd3944ea
    npm ERR! git clone --template=/Users/sklass/.npm/_git-remotes/_templates --mirror ssh://git@github.com/waterlock/waterlock-auth /Users/sklass/.npm/_git-remotes/ssh-git-github-com-waterlock-waterlock-auth-1d2279f6
    npm ERR! git clone --template=/Users/sklass/.npm/_git-remotes/_templates --mirror ssh://git@github.com/waterlock/waterlock-auth /Users/sklass/.npm/_git-remotes/ssh-git-github-com-waterlock-waterlock-auth-1d2279f6: Cloning into bare repository '/Users/sklass/.npm/_git-remotes/ssh-git-github-com-waterlock-waterlock-auth-1d2279f6'...
    npm ERR! git clone --template=/Users/sklass/.npm/_git-remotes/_templates --mirror ssh://git@github.com/waterlock/waterlock-auth /Users/sklass/.npm/_git-remotes/ssh-git-github-com-waterlock-waterlock-auth-1d2279f6: X11 forwarding request failed on channel 0
    npm ERR! git clone --template=/Users/sklass/.npm/_git-remotes/_templates --mirror ssh://git@github.com/waterlock/waterlock-auth /Users/sklass/.npm/_git-remotes/ssh-git-github-com-waterlock-waterlock-auth-1d2279f6: ERROR: Repository not found.
    npm ERR! git clone --template=/Users/sklass/.npm/_git-remotes/_templates --mirror ssh://git@github.com/waterlock/waterlock-auth /Users/sklass/.npm/_git-remotes/ssh-git-github-com-waterlock-waterlock-auth-1d2279f6: fatal: Could not read from remote repository.

Can you point me in the right direction?

Ref:
https://www.npmjs.com/package/waterlock-local-auth
