### ISSUE TITLE
get user id out of jwt object

### ISSUE THREAD

**Issue by pzontrop** [waterlock/waterlock-local-auth#24]
I would like to get the user object/identification out of the jwt object to send user specific replies.

Does waterlock provide a way to decode the jwt object? I have noticed that the allParams(req) from the utils only provides me with the encoded jwt object.

**Comment by praveenaj** [comment]
@pzontrop Can I know how you achieved this?

**Comment by pzontrop** [comment]
I didn't decode it, but if you like to,  you can look at the following example:
https://github.com/davidrivera/sails-waterlock-example/blob/master/api/policies/hasJsonWebToken.js

I just did the following in my controller:
var token = waterlock._utils.allParams(req).access_token;
UserService.findUserByToken(token).then(function(user) {
// Here you can extract user.id or whatever field you need.
}
