### ISSUE TITLE
Can't install npm module

### ISSUE THREAD

**Issue by Cellcote** [waterlock/waterlock-local-auth#26]
I get a warning stating that bcrypt can not be installed, and thus the waterlock-local-auth fails. In the main waterlock repository, some people state that bscryptjs should be used.

**Comment by GeoCloud** [comment]
+1

**Comment by smartcris** [comment]
+1

**Comment by gunish** [comment]
ive reverted the version in my local repo, try using this command to get past, until the owner's fix this 

npm install git+https://github.com/gunish/waterlock-local-auth.git

**Comment by Globegitter** [comment]
@Cellcote @Geocloud can you please try again with the latest version `0.0.6`

**Comment by wayne-o** [comment]
Guys please try now:

https://travis-ci.org/waterlock/waterlock-local-auth/builds/75943754

This was an issue related to the version of bcrypt and also the target node versions in local-auth
