### ISSUE TITLE
Return jwt on successful login

### ISSUE THREAD

**Issue by wimvanhouts** [waterlock/waterlock-local-auth#35]
Hi, 

why isn't the appropriate token not return after a successful call of the aut/login function in the response body? The call to user/jwt seems like yet another call, and, how are both calls linked to each other in this scenario? Do you use session or cookie to achieve this, and if so, doesn't that beat the whole point of using tokens in the first place?

Kind regards, 

Wim

**Comment by wayne-o** [comment]
There is a config switch for this- pretty sure the PR was merged in?

**Comment by wimvanhouts** [comment]
What would be the name of the config switch to enable this?

**Comment by wimvanhouts** [comment]
Ok, went through the list of PR's on the main waterlock project and found the solution. Instead of login success action to ''default" it must be set to "jwt", and in waterlock.js config file, it is best to set includeUserInJwtResponse to true, so you get all the information of the user at once. This makes it possible to work with sessions to get the token and works better in load balanced environment. Thx for the great component, but good docu seems to be missing at this time. Will try to write an article on it...

**Comment by wayne-o** [comment]
I'll spend some time in the next week synchronising things and see if I can
push it along a bit. I'm relatively new to the project so can't take any
credit for it :)
Docs definitely need updating and I'll see if I can get some of the PRs
merged in.

**Comment by wayne-o** [comment]
Ok so the documentation for this is on the main Waterlock README.md: https://github.com/waterlock/waterlock#config

Closing this now - feel free to re-open if you feel there is anything that needs adding / amending
