### ISSUE TITLE
Send mail when reset password is not working

### ISSUE THREAD

**Issue by carvilsi** [waterlock/waterlock-local-auth#40]
Hi!

I have an issue trying send an email when reset password.

I tried two versions of nodemailer 1.4.0 and 0.7.1 and with sails on silly log level I get the next message (I do not if it is related with the issue or not):

> Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).

In other hand I checked that nodemailer is working as standalone script and send emails correctly.

* sails 0.11.0
* waterlock 0.1.0
* waterlock-local-auth 0.0.6

By the way I tried with nodemailer 1.4.0 version, the PR proposed by @donmasakayan at https://github.com/waterlock/waterlock-local-auth/pull/22 and do not work.

If you have any clue to solve this issue I'll try my best to solve it (deprecation message to).

Thanks.

**Comment by mikeblakeney** [comment]
what are your mailer configs in waterlock config file?  I just implemented this yesterday in an application using mandrill and nodemailer and it works fine.  I'm still new to waterlock as well, but I dont mind trying to help.

**Comment by wayne-o** [comment]
I have this demo setup which is using all of the latest bits and it's working:

https://github.com/wayne-o/ember-waterlock-example

can you try and compare - see what might be different?

**Comment by carvilsi** [comment]
Thanks, I will try and tell you the result :smile:

**Comment by carvilsi** [comment]
Hi @wayne-o I tried to compare but the link that you provided is broken, 404 response.

**Comment by wayne-o** [comment]
Ah ok - I had to make that repo private - I'll do some tweaking and get another up asap - probably over the weekend - sorry for the mixup

**Comment by carvilsi** [comment]
Hi @wayne-o no problem and thanks :smile: 

I updated the nodemailer version to 1.5.0 and nodemailer-smtp-transport to 1.0.3, rewritten the mail config section on waterlock.js. And is working perfect!

Thanks.
