### ISSUE TITLE
Register Action

### ISSUE THREAD

**Issue by mrvini** [waterlock/waterlock-local-auth#43]
Hi, 

While working with sailsjs, came across waterlock module. I came across this post http://stackoverflow.com/questions/29944905/sails-js-waterlock-auth-register-causes-error-500?answertab=active#tab-top and was wondering if registration action is in works to be rolled out or should I use suggested solution

Thanks,
Val

**Comment by wayne-o** [comment]
It's in master but needs to be pushed to NPM - I'll try and see if we can get the final hurdle sorted.

**Comment by mrvini** [comment]
thank you @wayne-o
