### ISSUE TITLE
Password included in the response when PostAction is JWT

### ISSUE THREAD

**Issue by smartcris** [waterlock/waterlock-local-auth#47]
I'm building a SPA, using Sails.js only as a RESTful server and I'm a bit newbie on backend. I've configured Waterlock with includeUserInJwtResponse: true and in the login section I set postActions: JWT , but after logging in I get always the password hash  in the response. I would like to avoid sending the password to the client. I tried to configure the auth model in this way:
```
module.exports = {

  attributes: require('waterlock').models.auth.attributes({

    toJSON: function() {
      var obj = this.toObject();
      delete obj.password;
      return obj;
    }

  }),

  beforeCreate: require('waterlock').models.auth.beforeCreate,
  beforeUpdate: require('waterlock').models.auth.beforeUpdate
};
```

But it doesn't works.

another question: for a RESTful connection is it correct to configure the Sails policy in this way ?

```
'*': ['hasJsonWebToken'],

  AuthController:{
    'login':true
  },

```
 I'll really appreciate any help ;)
Thx

**Comment by mrvini** [comment]
you can update User model
```javascript
    toJSON: function () {
      var obj = this.toObject();
       if (typeof obj.auth === 'object' && obj.auth.password) {
          delete obj.auth.password;
       }
      return obj;
    }
```

**Comment by smartcris** [comment]
worked! 
thank you
