### ISSUE TITLE
Redirect after password reset

### ISSUE THREAD

**Issue by davidrivera** [waterlock/waterlock-local-auth#7]
Redirect after password reset

**Comment by wayne-o** [comment]
Does password reset rely on sessions? like - we are using JWT - will it work in this case?

**Comment by davidrivera** [comment]
@wayne-o  No password resets rely on the `resetToken` as during the process of a password reset the user would not have a valid session. If we are able to validate that token a password reset is issued. The fact that they are using jwt to authenticate is irrelevant as the endpoint to issue jwt's requires a username/password. I hope that clears things up.

**Comment by wayne-o** [comment]
@davidrivera  - where does the reset token live then? I can see we get sent back to the app via `forwardUrl` but there is no token in the URL nor in cookies?

**Comment by wayne-o** [comment]
We are only using the API btw with an ember front end - so the redirect goes to another domain:

api.sonatribe.com -> sonatribe.com

Will this be where the confusion is happening?

**Comment by davidrivera** [comment]
Alright heres the flow.

* you make a `POST` request to the reset endpoint which gets handled [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L62-L79) and [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L90-L106) provided a user email address
* a password reset gets created [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L93)
* then after the token is created we kick off an email which you can see [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/models/resetToken.js#L54-L80) but only if `passwordResetTokens` are enabled [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/models/resetToken.js#L57) and in your waterlock config
* the reset token `url` gets created and injected into the email template sent to the user [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/utils.js#L18-L25) and [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/models/resetToken.js#L60)
* the user clicks that in their email which does a `GET` request to the reset endpoint to validate that token [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L150)
* the user then gets sent to the `forwardUrl` [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L189) which i believe waterlock isn't currently responsible for. This forward url should be the location of a form on your site which does a `POST` request to the reset endpoint with a param of `password` being the password you would like to change the users account to [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L116)

It seems you are right the reset token is expecting to be in the session [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L68) we could just pass it in as another param and do a check against that instead at that same spot. If you guys agree. I hope this cleared up more for you, sorry for the verbosity :smile:

**Comment by wayne-o** [comment]
so yeah - the confusion for me is the last bullet - we would just receive a GET request to /passwordreset or whatever with no idea who the user is... so we wouldn't know who the password reset request is being processed for and whether they are who they say they are.

I also noticed the redirect URL doesn't obey the pluralized config - I'll submit a PR for that in the am - i'm just trying to figure out the rest for the moment :)

**Comment by davidrivera** [comment]
Yea so the idea is that you really don't need to know who the reset is for as there's no real way to be certain. We can try to assume it is a specific user by the fact they clicked a like in their email, but we can't know it's them. So your front end is given a token which is valid for a short period (fyi they are given a jwt with a smaller expiration date) they can use that token to do a password reset. Thanks a bunch and let me know if you need anything else cleared up!

**Comment by wayne-o** [comment]
Where is the JWT when it goes to the redirect though? there's no cookies or anything?

**Comment by davidrivera** [comment]
Ah you're right the jwt doesn't get passed along in [the redirect](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L189). It does get put into the session [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L186). This is also an easy fix. We could switch on the sessionless config value and either put it into the session or pass it along in [the redirect](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L189)

**Comment by wayne-o** [comment]
In the redirect as a query param?

Let me know and I'll bosh it all together on my commute tomoz :)

**Comment by davidrivera** [comment]
haha yea just redirect with a query param should be a simple fix. Be sure to switch on that stateless waterlock config value if you're going to implement it. It would be silly for the token to be serialized into the session and passed as a query param we only need one. :wink: Thanks a bunch man! You're awesome!

**Comment by wayne-o** [comment]
OK so my PR is in - final 2 Qs from me :)

 - should I be checking the stateless config and only serializing into the URL if that is true? I suspect so but just wanted to check

 - does waterlock-local-auth take care of the actual password resetting? or is that just a save on the user object?

**Comment by wayne-o** [comment]
Does waterlock-local-auth handle the actual resetting of the password?

**Comment by davidrivera** [comment]
@wayne-o yes you can see [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L116) and [here](https://github.com/waterlock/waterlock-local-auth/blob/master/lib/controllers/actions/reset.js#L71) making a `POST` request to reset password endpoint with the new password.
